### ISSUE TITLE
Regression on getting address in CONTEXT

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#535]
Most probably a regression from #533:

```
Red/System []

c: context [
    x: 0
    print :x
]
```

-= Red/System Compiler =- 
**\* Compilation Error: undefined symbol: x 
**\* at line: 5 
**\* near: [:x]
