### ISSUE TITLE
WITH misses #import

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#379]
Probably a regression from #348:

```
Red/System []

c: context [
    #import [LIBC-file cdecl [
        print-error: "perror" [  ; Print error to stderr.
            string      [c-string!]
        ]
    ]]
]
c/print-error "."
with c [
    print-error "!"
]
```

-= Red/System Compiler =- 
Compiling /home/kaj/Red/SQLite/examples/test.reds ...
**\* Compilation Error: undefined symbol: print-error 
**\* at line: 12 
**\* near: [
    print-error "!"
]
