### ISSUE TITLE
red.r doesn't detect Red/System file

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#538]
A regression from #537:

```
Red/System []
```

-=== Red Compiler 0.3.3 ===- 

Compiling /home/kaj/Red/REBOL-3/examples/test.reds ...

Compiling to native code...
**\* Compilation Error: source is not a Red/System program 
**\* in file: %_**sys-global.reds 
*_\* at line: 1 
**\* near: []
